/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rsi;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Asus
 */
public class HapusJadwalAgenda extends javax.swing.JFrame {
    private DefaultTableModel tableModel;

    /**
     * Creates new form Hapus_Jadwal_Agenda
     */
    
    public HapusJadwalAgenda() {
        this("", "", null); // Panggil constructor utama dengan nilai default
    }
    
    public HapusJadwalAgenda(String namaAgenda, String waktuAgenda, java.util.Date tanggalAgenda) {
        initComponents();
        initializeTable();
        Bhapus.setForeground(java.awt.Color.WHITE);
        BKembali.setForeground(java.awt.Color.WHITE);
    }
    
    private void centerTableHeader() {
        JTableHeader header = jTable1.getTableHeader();
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer(); 
        headerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER); 
        header.setDefaultRenderer(headerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JnamaAgenda = new javax.swing.JLabel();
        jWaktuAgenda = new javax.swing.JLabel();
        jTanggalAgenda = new javax.swing.JLabel();
        BKembali = new javax.swing.JButton();
        Bhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        IsiNamaAgenda = new javax.swing.JLabel();
        IsiWaktuAgenda = new javax.swing.JLabel();
        IsiTanggalAgenda1 = new javax.swing.JLabel();
        BgHapusJadwal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JnamaAgenda.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JnamaAgenda.setForeground(new java.awt.Color(0, 0, 0));
        JnamaAgenda.setText("Nama Agenda    :");
        getContentPane().add(JnamaAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jWaktuAgenda.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jWaktuAgenda.setForeground(new java.awt.Color(0, 0, 0));
        jWaktuAgenda.setText("Waktu Agenda   :");
        getContentPane().add(jWaktuAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        jTanggalAgenda.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTanggalAgenda.setForeground(new java.awt.Color(0, 0, 0));
        jTanggalAgenda.setText("Tanggal              :");
        getContentPane().add(jTanggalAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        BKembali.setBackground(new java.awt.Color(51, 0, 0));
        BKembali.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BKembali.setText("KEMBALI");
        BKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(BKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 140, 40));

        Bhapus.setBackground(new java.awt.Color(0, 51, 51));
        Bhapus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Bhapus.setText("HAPUS");
        Bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhapusActionPerformed(evt);
            }
        });
        getContentPane().add(Bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 130, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NAMA", "WAKTU", "TANGGAL"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 102));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 400, 280));

        IsiNamaAgenda.setBackground(new java.awt.Color(153, 153, 153));
        IsiNamaAgenda.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(IsiNamaAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 400, 40));

        IsiWaktuAgenda.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(IsiWaktuAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 400, 40));

        IsiTanggalAgenda1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(IsiTanggalAgenda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 400, 40));

        BgHapusJadwal.setIcon(new javax.swing.ImageIcon("D:\\image\\Frame Hapus Jadwal Agenda.png")); // NOI18N
        BgHapusJadwal.setText("jLabel1");
        getContentPane().add(BgHapusJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKembaliActionPerformed
        // TODO add your handling code here:
        String namaAgenda = IsiNamaAgenda.getText().trim(); 
        String waktuAgenda = IsiWaktuAgenda.getText().trim(); 
        String tanggalStr = IsiTanggalAgenda1.getText().trim(); 

        if (!namaAgenda.isEmpty() || !waktuAgenda.isEmpty() || !tanggalStr.isEmpty()) {
            int response = javax.swing.JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin membatalkan penghapusan jadwal agenda?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);

            if (response == javax.swing.JOptionPane.YES_OPTION) {
                DashboardAdministrator dashboardAdmin = new DashboardAdministrator();
                dashboardAdmin.setVisible(true);
                this.dispose(); // Tutup halaman saat ini
            }
        } else {
            DashboardAdministrator dashboardAdmin = new DashboardAdministrator();
            dashboardAdmin.setVisible(true);
            this.dispose(); // Tutup halaman saat ini
        }
    }//GEN-LAST:event_BKembaliActionPerformed

    private void BhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhapusActionPerformed
        // TODO add your handling code here:
        String namaAgenda = IsiNamaAgenda.getText();
        String waktuAgenda = IsiWaktuAgenda.getText();
        String tanggalStr = IsiTanggalAgenda1.getText();

        if (namaAgenda.isEmpty() || waktuAgenda.isEmpty() || tanggalStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Konversi string tanggal ke java.util.Date
        java.util.Date tanggalAgenda = null;
        try {
            tanggalAgenda = new SimpleDateFormat("dd-MM-yyyy").parse(tanggalStr);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Format tanggal tidak valid.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return;
        }

        // Tampilkan pesan konfirmasi sebelum menghapus
        int response = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin menghapus agenda ini? Data tidak akan dikembalikan.",
                "Konfirmasi Penghapusan",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (response == javax.swing.JOptionPane.YES_OPTION) {
            try (ControlAgenda db = new ControlAgenda()) {
                boolean success = db.hapusAgenda(namaAgenda, waktuAgenda, tanggalAgenda);
                if (success) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Agenda berhasil dihapus!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                    // Perbarui tabel tanpa meninggalkan halaman
                    loadAgendaData();

                    // Kosongkan JLabel setelah penghapusan
                    IsiNamaAgenda.setText("");
                    IsiWaktuAgenda.setText("");
                    IsiTanggalAgenda1.setText("");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Agenda tidak ditemukan atau gagal dihapus.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus agenda.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BhapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            // Ambil data dari tabel berdasarkan baris yang dipilih
            int id = (int) tableModel.getValueAt(selectedRow, 0);
            String namaAgenda = (String) tableModel.getValueAt(selectedRow, 1);
            String waktuAgenda = (String) tableModel.getValueAt(selectedRow, 2);
            String tanggalStr = (String) tableModel.getValueAt(selectedRow, 3);

            // Konversi string tanggal ke java.util.Date
            Date tanggalAgenda = null;
            try {
                tanggalAgenda = new SimpleDateFormat("dd-MM-yyyy").parse(tanggalStr);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Format tanggal tidak valid.", "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }

            // Set data ke form
            IsiNamaAgenda.setText(namaAgenda);
            IsiWaktuAgenda.setText(waktuAgenda);
            IsiTanggalAgenda1.setText(new SimpleDateFormat("dd-MM-yyyy").format(tanggalAgenda));
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void initializeTable() {
        tableModel = (DefaultTableModel) jTable1.getModel();
        loadAgendaData();
        centerTableHeader();
    }

    private void loadAgendaData() {
        try (ControlAgenda db = new ControlAgenda()) {
            List<DataAgenda> agendaList = db.tampilAgenda();
            tableModel.setRowCount(0); // Clear existing data

            if (agendaList.isEmpty()) {
                System.out.println("Tidak ada data agenda.");
            }

            for (DataAgenda agenda : agendaList) {
                Object[] row = {
                    agenda.getId(),
                    agenda.getNama(),
                    agenda.getWaktu(),
                    new SimpleDateFormat("dd-MM-yyyy").format(agenda.getTanggal())
                };
                tableModel.addRow(row);
            }

            // Panggil untuk menyesuaikan lebar kolom setelah data dimuat
            adjustTableColumnWidths();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengambil data agenda: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    private void adjustTableColumnWidths() {
        // Dapatkan column model dari tabel
        javax.swing.table.TableColumnModel columnModel = jTable1.getColumnModel();

        // Set lebar untuk setiap kolom
        columnModel.getColumn(0).setPreferredWidth(50);  // ID lebih sempit
        columnModel.getColumn(1).setPreferredWidth(200); // Nama lebih lebar
        columnModel.getColumn(2).setPreferredWidth(150); // Waktu cukup lebar
        columnModel.getColumn(3).setPreferredWidth(100); // Tanggal lebar sesuai format tanggal
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HapusJadwalAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HapusJadwalAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HapusJadwalAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HapusJadwalAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HapusJadwalAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BKembali;
    private javax.swing.JLabel BgHapusJadwal;
    private javax.swing.JButton Bhapus;
    private javax.swing.JLabel IsiNamaAgenda;
    private javax.swing.JLabel IsiTanggalAgenda1;
    private javax.swing.JLabel IsiWaktuAgenda;
    private javax.swing.JLabel JnamaAgenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTanggalAgenda;
    private javax.swing.JLabel jWaktuAgenda;
    // End of variables declaration//GEN-END:variables
}
