/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rsi;

/**
 *
 * @author DEVINDA HERAST
 */
public class UploadWebinar extends javax.swing.JFrame {

    /**
     * Creates new form UploadWebinar
     */
    public UploadWebinar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        LinkPendaftaran = new javax.swing.JLabel();
        TextBoxTanggalWaktu = new javax.swing.JTextField();
        TanggalWaktu = new javax.swing.JLabel();
        TextboxDeskripsi = new javax.swing.JTextField();
        Deskripsi = new javax.swing.JLabel();
        TextboxJudul = new javax.swing.JTextField();
        Judul = new javax.swing.JLabel();
        BackgroundUpload = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 0));
        jButton2.setText("SIMPAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 100, 30));

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 0));
        jButton1.setText("KEMBALI");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, 30));

        jTextField4.setBackground(new java.awt.Color(172, 189, 155));
        jTextField4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 570, 30));

        LinkPendaftaran.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        LinkPendaftaran.setForeground(new java.awt.Color(255, 255, 255));
        LinkPendaftaran.setText("LINK PENDAFTARAN");
        getContentPane().add(LinkPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        TextBoxTanggalWaktu.setBackground(new java.awt.Color(172, 189, 155));
        TextBoxTanggalWaktu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(TextBoxTanggalWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 570, 30));

        TanggalWaktu.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        TanggalWaktu.setForeground(new java.awt.Color(255, 255, 255));
        TanggalWaktu.setText("TANGGAL, WAKTU");
        getContentPane().add(TanggalWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        TextboxDeskripsi.setBackground(new java.awt.Color(172, 189, 155));
        TextboxDeskripsi.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(TextboxDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 570, 30));

        Deskripsi.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        Deskripsi.setForeground(new java.awt.Color(255, 255, 255));
        Deskripsi.setText("DESKRIPSI");
        getContentPane().add(Deskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        TextboxJudul.setBackground(new java.awt.Color(172, 189, 155));
        TextboxJudul.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TextboxJudul.setCaretColor(new java.awt.Color(255, 255, 255));
        TextboxJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextboxJudulActionPerformed(evt);
            }
        });
        getContentPane().add(TextboxJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 570, 30));

        Judul.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        Judul.setForeground(new java.awt.Color(255, 255, 255));
        Judul.setText("JUDUL");
        getContentPane().add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        BackgroundUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rsi/Image/Frame Upload Informasi Webinar Administrator.png"))); // NOI18N
        BackgroundUpload.setText("jLabel1");
        getContentPane().add(BackgroundUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TextboxJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextboxJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextboxJudulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadWebinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadWebinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadWebinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadWebinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UploadWebinar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundUpload;
    private javax.swing.JLabel Deskripsi;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel LinkPendaftaran;
    private javax.swing.JLabel TanggalWaktu;
    private javax.swing.JTextField TextBoxTanggalWaktu;
    private javax.swing.JTextField TextboxDeskripsi;
    private javax.swing.JTextField TextboxJudul;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
